[package]
name = "libos"
version = "0.1.0"
edition = "2024"

[features]
# Use an 8 MiB heap instead of the default 2 MiB.  Enable for vfs-server which
# needs to cache the entire initrd TAR in memory.
large-heap = []
# Use a 32 MiB heap.  Enable for pkg which must buffer Packages.gz (compressed
# + decompressed) entirely in memory before writing the index to disk.
huge-heap = []

[dependencies]
buddy_system_allocator = "0.11.0"
vfs-proto = { path = "../vfs-proto" }
pm-proto = { path = "../pm-proto" }
