//! # Initial Ramdisk (Initrd) Support
//!
//! This module provides support for the initial ramdisk (initrd), which is a
//! file system image that is loaded into memory by the bootloader and made
//! available to the kernel. The initrd typically contains the root file system
//! and boot-time utilities needed to bring the system up before the real root
//! file system is mounted.
//!
//! ## TAR Format
//!
//! OpenV's initrd uses the TAR (Tape Archive) format, which is a simple,
//! widely-supported archive format. The TAR format consists of a series of
//! 512-byte headers followed by file data, also aligned to 512-byte blocks.
//!
//! Each TAR header contains:
//!
//! - **Name** (100 bytes): The file name, null-terminated
//! - **Mode** (8 bytes): File permissions in octal
//! - **UID** (8 bytes): User ID in octal
//! - **GID** (8 bytes): Group ID in octal
//! - **Size** (12 bytes): File size in octal
//! - **Mtime** (12 bytes): Modification time in octal
//! - **Checksum** (8 bytes): Header checksum
//! - **Typeflag** (1 byte): File type ('0' or 0 for regular file)
//! - **Linkname** (100 bytes): Name of linked file
//!
//! ## Usage
//!
//! The initrd is initialized once during kernel boot from the DTB's
//! `linux,initrd-start` and `linux,initrd-end` properties. After initialization,
//! files can be looked up by name using [`kernel_initrd_lookup`].
//!
//! This module is used primarily by `posix_spawn` and `sys_exec` to load
//! binaries before the VFS server is running.
//!
//! ## Limitations
//!
//! This is a minimal TAR parser that only supports:
//!
//! - Regular files (typeflag '0' or 0)
//! - Linear scanning (no index)
//! - Exact name matching
//!
//! It does not support directories, symbolic links, or other TAR features.

use spin::Once;

/// Storage for the initrd data.
///
/// The initrd is stored as a static reference to a byte slice. It is initialized
/// once during kernel boot via [`init`] and never modified thereafter. The use
/// of [`Once`] ensures that the initrd is initialized exactly once, even in
/// the presence of concurrent calls to [`init`].
static INITRD_DATA: Once<Option<&'static [u8]>> = Once::new();

/// Initializes the initrd with the provided data.
///
/// This function should be called once during kernel boot, typically from
/// [`kmain`], to provide the kernel with the initrd data. Subsequent calls
/// are silently ignored (the first call wins).
///
/// # Arguments
///
/// * `data` - A static byte slice containing the initrd data. The slice must
///   remain valid for the lifetime of the kernel, as it is stored in a
///   [`Once`] and accessed later via [`kernel_initrd_lookup`].
///
/// # Safety
///
/// The caller must ensure that:
///
/// - `data` points to valid memory containing a valid TAR archive.
/// - `data` remains valid for the lifetime of the kernel.
/// - This function is called at most once (subsequent calls are no-ops).
///
/// [`kmain`]: ../fn.kmain.html
/// [`Once`]: https://docs.rs/spin/latest/spin/struct.Once.html
pub unsafe fn init(data: &'static [u8]) {
    INITRD_DATA.call_once(|| Some(data));
}

/// Looks up a file in the initrd by exact name.
///
/// This function scans the initrd linearly, looking for a file with the
/// specified name. It returns the file's contents as a static byte slice if
/// found.
///
/// # Arguments
///
/// * `path` - The path of the file to look up. The leading slash is optional
///   and will be stripped before matching. The path is matched exactly,
///   including the directory prefix (e.g., "bin/ls" will not match "ls").
///
/// # Returns
///
/// A static byte slice containing the file's contents if found, or `None`
/// if the file is not present in the initrd.
///
/// # Algorithm
///
/// The function performs a linear scan of the TAR archive, parsing each
/// 512-byte header to extract the file name, size, and type. It advances
/// past each file's data (aligned to 512 bytes) until it finds a match
/// or reaches the end of the archive.
///
/// # macOS Resource Forks
///
/// The function automatically skips macOS resource-fork entries, which are
/// files starting with `._`. These files are metadata generated by macOS
/// and should not be loaded as executables.
///
/// # Safety
///
/// The returned slice borrows from the initrd data, which has a static
/// lifetime. However, the underlying memory may be reused for other
/// purposes if the initrd is unmounted (which OpenV does not currently
/// support). Callers should not modify the contents of the returned slice.
///
/// # Example
///
/// ```ignore
/// if let Some(data) = kernel_initrd_lookup("/init") {
///     // Load the init binary from `data`...
/// }
/// ```
pub fn kernel_initrd_lookup(path: &str) -> Option<&'static [u8]> {
    let data = INITRD_DATA.get()?.expect("Initrd data not initialized");
    let mut offset = 0;

    // Remove leading slash for matching since TAR paths usually don't have it,
    // or just match exact component. 
    // In our initrd TAR, paths are usually like "init", "bin/ls", etc.
    let target = path.trim_start_matches('/');

    // Scan the TAR archive linearly. Each file consists of a 512-byte header
    // followed by the file data, aligned to 512-byte blocks.
    while offset + 512 <= data.len() {
        let header = &data[offset..offset + 512];

        // An all-zero header marks the end of the TAR archive.
        if header.iter().all(|&b| b == 0) {
            break; // End of archive
        }

        // Extract the file name from the header. The name is null-terminated
        // and at most 100 bytes long.
        let mut name_len = 0;
        while name_len < 100 && header[name_len] != 0 {
            name_len += 1;
        }
        let name_str = core::str::from_utf8(&header[0..name_len]).unwrap_or("");

        // Extract the file size from the header. The size is stored as a
        // 12-byte octal number in bytes 124-135.
        let mut size = 0;
        for i in 124..135 {
            let b = header[i];
            if b >= b'0' && b <= b'7' {
                size = (size << 3) | (b - b'0') as usize;
            }
        }

        // The typeflag is at byte 156. '0' or 0 indicates a regular file.
        let typeflag = header[156];
        offset += 512; // Advance past header

        // Regular file — skip macOS resource-fork entries (._<name>)
        if typeflag == b'0' || typeflag == 0 {
            // Clean up the name by removing leading "./" and "/".
            let clean_name = name_str.trim_start_matches("./").trim_start_matches("/");
            // Skip ._ resource-fork metadata files generated by macOS tar
            let base = clean_name.rsplit('/').next().unwrap_or(clean_name);
            if base.starts_with("._") {
                offset += (size + 511) & !511;
                continue;
            }
            // Check if this file matches the requested path.
            if clean_name == target {
                // Bounds check: ensure the file data is within the archive.
                if offset + size > data.len() {
                    return None;
                }
                // SAFETY: We've verified that `offset + size` is within `data`,
                // so this slice is valid for reads of `size` bytes.
                let file_slice = unsafe { core::slice::from_raw_parts(data.as_ptr().add(offset), size) };
                return Some(file_slice);
            }
        }

        // Advance past data, aligned to 512 blocks
        offset += (size + 511) & !511;
    }

    None
}
